CREATE TABLE IF NOT EXISTS users
(
    user_id    bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email      varchar(150) NOT NULL,
    user_name  varchar(200) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id    bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name  varchar(200) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT unique_category_name UNIQUE (category_name)
);