CREATE TABLE IF NOT EXISTS users
(
    user_id   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email     varchar(150) NOT NULL,
    user_name varchar(200) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_name varchar(200) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT unique_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    latitude    double not null,
    longitude   double not null,
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id    bigint                  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_title varchar(120)            NOT NULL,
    annotation  varchar(2000)           NOT NULL,
    category_id bigint                  NOT NULL,
    created_on  timestamp NOT NULL,
    description varchar(7000)           NOT NULL,
    eventDate   timestamp               NOT NULL,
    location_id bigint                  NOT NULL,
    user_id bigint NOT NULL,
    paid boolean not null,
    participation_limit int DEFAULT 0,
    published_on timestamp,
    request_moderation boolean DEFAULT false,
    state varchar(12) not null,
    CONSTRAINT events_pkey PRIMARY KEY (event_id),
    CONSTRAINT fk_event_category
        FOREIGN KEY (category_id)
            REFERENCES categories (category_id),
    CONSTRAINT fk_event_location
        FOREIGN KEY (location_id)
            REFERENCES locations (location_id),
    CONSTRAINT fk_event_initiator
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);