CREATE TABLE IF NOT EXISTS endpoint_hits
(
    hit_id        bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app           varchar(100)             NOT NULL,
    uri           varchar(100)             NOT NULL,
    ip            varchar(20)              NOT NULL,
    hit_timestamp timestamp with time zone NOT NULL,
    CONSTRAINT hit_pkey PRIMARY KEY (hit_id)
);